services:
  - type: worker
    name: pg-backups
    env: ruby
    region: frankfurt
    buildCommand: ./render-build.sh
    startCommand: ./render-start.sh

    disk:
      name: pg-backups
      mountPath: /opt/backups
      sizeGB: 10 # optional

